name: bayesian-deepkriging
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - geopandas=1.0.1
  - matplotlib=3.7.3
  - numpy=1.24.4
  - pandas=2.0.3
  - scikit-learn=1.6.0
  - scipy=1.13.1
  - tensorflow=2.16.1
  - tensorflow-probability=0.24.0
  - pip
  - pip:
      - keras==3.5.0
